import { SITE_URL } from '@/lib/og';

/** Hostname only — Yandex Host rules reject a scheme; Google ignores Host. */
export const SITE_HOST = new URL(SITE_URL).host;

/**
 * Visibility-first AI + multi-engine robots.txt (multi-engine-master-plan sections 7-8).
 *
 * Allow search/citation crawlers; block training-only tokens.
 * Yandex: Clean-param + full rule set under User-agent: Yandex (* is ignored when a Yandex block exists).
 * Served as plain text so Clean-param is preserved (MetadataRoute.Robots cannot emit it).
 */
export function buildRobotsTxt(): string {
  // Single canonical sitemap declaration. /sitemap.xml rewrites to the sharded
  // /sitemap-index route (next.config.ts), so a second Sitemap line is redundant.
  const sitemapIndex = `${SITE_URL}/sitemap.xml`;

  const lines: string[] = [
    '# RKC Automotive — multi-engine + AI citation policy',
    `# Generated for ${SITE_HOST}. Never emit Copilot opt-out meta (archive/cache bans).`,
    '',
    '# --- Default ---',
    'User-agent: *',
    'Allow: /',
    'Allow: /llms.txt',
    'Allow: /.well-known/llms.txt',
    '',
    '# --- Major search engines ---',
    'User-agent: Googlebot',
    'Allow: /',
    '',
    'User-agent: Bingbot',
    'Allow: /',
    '',
    'User-agent: DuckDuckBot',
    'Allow: /',
    '',
    'User-agent: Yeti',
    'Allow: /',
    '',
    'User-agent: SeznamBot',
    'Allow: /',
    '',
    'User-agent: Qwantbot',
    'Allow: /',
    '',
    'User-agent: MojeekBot',
    'Allow: /',
    '',
    'User-agent: Amazonbot',
    'Allow: /',
    '',
    '# --- AI search / citation (allow) ---',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    '',
    'User-agent: ChatGPT-User',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    'User-agent: Claude-SearchBot',
    'Allow: /',
    '',
    'User-agent: Claude-User',
    'Allow: /',
    '',
    'User-agent: Meta-WebIndexer',
    'Allow: /',
    '',
    'User-agent: DuckAssistBot',
    'Allow: /',
    '',
    'User-agent: Applebot',
    'Allow: /',
    '',
    '# --- AI training (block — visibility without training consent) ---',
    'User-agent: GPTBot',
    'Disallow: /',
    '',
    'User-agent: ClaudeBot',
    'Disallow: /',
    '',
    'User-agent: Google-Extended',
    'Disallow: /',
    '',
    'User-agent: Meta-ExternalAgent',
    'Disallow: /',
    '',
    'User-agent: meta-externalagent',
    'Disallow: /',
    '',
    'User-agent: CCBot',
    'Disallow: /',
    '',
    'User-agent: Applebot-Extended',
    'Disallow: /',
    '',
    'User-agent: Bytespider',
    'Disallow: /',
    '',
    'User-agent: cohere-ai',
    'Disallow: /',
    '',
    '# --- Yandex (must duplicate Allow; * ignored when this block exists) ---',
    'User-agent: Yandex',
    'Allow: /',
    'Allow: /llms.txt',
    'Allow: /.well-known/llms.txt',
    // Tracking / ad params — merges duplicates and transfers metrics (Yandex Clean-param).
    'Clean-param: utm_source&utm_medium&utm_campaign&utm_term&utm_content&utm_id&gclid&gbraid&wbraid&fbclid&msclkid&mc_cid&mc_eid&yclid&ysclid&yrclid&_ga&_gl&ref',
    '',
    '# Prefer Neuro/AI answers to cite us (do not block YandexAdditionalBot)',
    'User-agent: YandexAdditionalBot',
    'Allow: /',
    '',
    'User-agent: YandexAdditional',
    'Allow: /',
    '',
    `Host: ${SITE_HOST}`,
    `Sitemap: ${sitemapIndex}`,
    '',
  ];

  return lines.join('\n');
}
